from src.plotter.toy import ToyPlotterCallback
from src.plotter.benchmark_hdg import BenchmarkHDGPlotterCallback
from src.plotter.benchmark_image import BenchmarkImagePlotterCallback
from src.plotter.benchmark_text import BenchmarkTextPlotterCallback