from src.metrics.callbacks.benchmark_hdg import BenchmarkHDGMetricsCallback
from src.metrics.callbacks.benchmark_image import BenchmarkImageMetricsCallback
from src.metrics.callbacks.benchmark_text import BenchmarkTextMetricsCallback